Added Telemetry Ingest assets for wfs
newrelic-experimental/nr1-innovation-cicd pull request #2
Opened 2021-03-29 21:02 UTC by hsinghkalsi

Added  BitbucketToInsights & JiraToInsights assets to assist with webhook integrations

2021-03-29 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic-experimental/nr1-innovation-cicd?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic-experimental/nr1-innovation-cicd?pullRequest=2) before we can accept your contribution.<br/><hr/>**hsinghkalsi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic-experimental/nr1-innovation-cicd?pullRequest=2) it.</sub>

2021-03-29 21:11 UTC, aso1124 requested changes
Should we remove the mention of Heroku? I don't think this is specifically something that needs to run on Heroku, and that might cause some users confusion.

2021-03-29 21:16 UTC, hsinghkalsi commented
@aso1124  Removed Heroku reference. we want to keep it generic, its node so really the only thing we need to make sure is to make sure user understand what the URL should look like

2021-03-29 21:23 UTC, aso1124 approved these changes

2021-04-01 04:51 UTC, shahramk approved these changes

2021-04-01 14:23 UTC, merged